### ISSUE TITLE
Suggestion: rename --ci option to a context-neutral name

### ISSUE THREAD

**Issue by fvsch** [skryukov/rubocop-gradual#1]
The `--ci` option is ambiguous:

- Continuous integration covers a wide range of practices.
- It suggests that this command should only be ran on CI servers, but it might be useful to run it on developer workstations as well.
- It doesn't actually describe what the option does.

If the functionality is "check code against the lock file and error out if there is any new linting output", maybe a name like `--check` might be a better fit?

Edit: other brainstormed names: `--test`, `--strict`.

**Comment by fvsch** [comment]
Another option would be a design where the following behaviors are separated:

1. erroring out on new linting output
2. how to modify the lock file: no modification, bookkeeping and removing issues only, or adding new issues

I think that erroring out if there are new issues could be the default, so that the `--ci` or `--strict` option isn't even needed. There could be options for managing the lock file update mode.

Something like:

```sh
# Default: errors out on new issues, updates lock file
# with positive changes if there are no new issues
rubocop-gradual

# For CI, might be useful to disable updating so that
# it doesn't modify files
rubocop-gradual --no-update

# Forcing updates, should never error out
# (except for errors in rubocop-gradual, IO errors, etc.)
rubocop-gradual --update
```

In that model, I’m a bit unclear if `rubocop-gradual` should only update the lock file with neutral (bookkeeping) and positive (issue removal) changes _if there were also no new issues_ (meaning that the lock file stays untouched if there is any new issue), or if it should still update the lock file with neutral/positive changes _and_ error out. I think Betterer might take the second option?

**Comment by skryukov** [comment]
Hey, @fvsch thanks for the issue!

Overall, I agree to your suggestions. Love the `--force-update`, but it seems to me unclear that `rubocop-gradual --no-update` returns error even when positive changes occurs. I assume this option would mean `--dry-run` 🤔 Maybe we can refer what we are trying to do with `--ci` option: `--assert-lock-file` or something like this?

```
# Default: errors out on new issues, updates lock file
# with positive changes if there are no new issues
rubocop-gradual

# Disable updating so that it doesn't modify files,
# but still returns the same error code
rubocop-gradual --dry-run

# For CI, checks if lock file is updated
rubocop-gradual --assert-lock-file

# Forcing updates, should never error out
# (except for errors in rubocop-gradual, IO errors, etc.)
rubocop-gradual --force-update
```

> In that model, I’m a bit unclear if `rubocop-gradual` should only update the lock file with neutral (bookkeeping) and positive (issue removal) changes if there were also no new issues (meaning that the lock file stays untouched if there is any new issue), or if it should still update the lock file with neutral/positive changes and error out. I think Betterer might take the second option?

I think it should update only when there are no errors because partial update might lead to overuse of force updating:
- user moves a code with offense to another file
- runs `rubocop-gradual`, which removes that offense from the lock file, but errors out for a "new" offense
- at this point, user can't undo that action without force updating lock file

**Comment by fvsch** [comment]
After a bit more discussion, the idea is to keep `rubocop-gradual` without options as a command that is feature-full, can error out and have side-effects, because that's a common pattern in the Ruby world (opinionated defaults).

So, keeping rubocop-gradual as a command with side-effects, intended for the main development workflow:

1. The main change would be to rename `--ci` to something like `--check` or `--test`.
2. It might be useful to rename `--update` to `--force-update`, and to remove the short `-u` version, because:
    - if the default command already updates the lock file, `--update` is ambiguous
    - it might be a useful signal to use that "force" keyword, since it signals that it should be a somewhat exceptional or rare occurrence?
    - and if it should be exceptional or rare, maybe having a short `-u` version is a footgun?
2. I think a `--dry-run` (or `--no-update`) option is not needed (again, given ecosystem conventions), at least initially.
    - If you need to check the lock file against the current codebase, there's the `--check` option for that already, and we don't want to incentivise doing some form of loose checking.
    - If there's a strong need, there will be feature requests later on. 

So I would consider this issue solved if the `--ci` option gets renamed to something more neutral (and explicit about what it does).

I’ll open another issue about the `--update` option.
