### ISSUE TITLE
Odd encoding churn

### ISSUE THREAD

**Issue by pboling** [skryukov/rubocop-gradual#16]
Running rubocop-gradual is resulting in many iterations of churn between encoded strings and unencoded strings across the entire lockfile.  Some pics of one of the recent ones:

First we went one way:
<img width="1058" alt="Screenshot 2023-10-23 at 23 06 15" src="https://github.com/skryukov/rubocop-gradual/assets/19505/f0e9afb4-9039-42fb-9fc7-d8bc1a9426e7">
<img width="1058" alt="Screenshot 2023-10-23 at 23 06 05" src="https://github.com/skryukov/rubocop-gradual/assets/19505/4bd90422-e52d-4698-af09-5282846f27b2">
<img width="1058" alt="Screenshot 2023-10-23 at 23 05 40" src="https://github.com/skryukov/rubocop-gradual/assets/19505/9c63a946-921c-43de-bc21-8e83042b2b6c">
<img width="1058" alt="Screenshot 2023-10-23 at 23 05 32" src="https://github.com/skryukov/rubocop-gradual/assets/19505/0cb3a412-6106-4b6c-9d9e-c32840e39185">

And then later the same day:
<img width="1058" alt="Screenshot 2023-10-23 at 23 01 55" src="https://github.com/skryukov/rubocop-gradual/assets/19505/685b665d-6b43-44bd-8e25-5f536686ce99">
<img width="1058" alt="Screenshot 2023-10-23 at 23 01 47" src="https://github.com/skryukov/rubocop-gradual/assets/19505/b5f62796-f079-45de-b2f3-90708961a85a">
<img width="1058" alt="Screenshot 2023-10-23 at 23 01 19" src="https://github.com/skryukov/rubocop-gradual/assets/19505/b11114be-9a7c-4510-8ca2-e3bfdd4464d6">
<img width="1058" alt="Screenshot 2023-10-23 at 23 01 04" src="https://github.com/skryukov/rubocop-gradual/assets/19505/ea52e7ec-356f-4cf7-ac38-998d8ae00b5b">

**Comment by skryukov** [comment]
Hey, @pboling, thanks for the report! No changes in os/ruby/rubocop versions, right? Is there a link to CI run or any other info I can use?

**Comment by pboling** [comment]
Correct, no changes in version, or anything else.  The churn is coming from different developers' computers, however on my machine alone I have seen it churn in both directions.

There is no public source or build in this case, unfortunately.
